import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createHash, randomBytes } from 'node:crypto';

/*
 * File storage behind one small interface, so business code never knows
 * where bytes live: a folder on the local disk (development) or Cloudinary
 * (production), selected by STORAGE_DRIVER. Another provider is added by
 * implementing FileStorage — nothing else changes.
 *
 * Keys are generated by the application (never taken from a user's file
 * name) and are never shown to users; files are served through
 * permission-checked routes by document id.
 */

export interface FileStorage {
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  /** The stored bytes, or null if the object doesn't exist. */
  get(key: string): Promise<Buffer | null>;
}

const KEY_PATTERN = /^[a-z0-9][a-z0-9/_.-]{0,300}$/;

function assertKey(key: string) {
  if (!KEY_PATTERN.test(key) || key.includes('..') || key.includes('//')) {
    throw new Error('Invalid storage key.');
  }
}

/** Development storage: files under LOCAL_STORAGE_DIR (default ./.local-storage, git-ignored). */
class LocalDiskStorage implements FileStorage {
  constructor(private readonly root: string) {}

  private pathFor(key: string) {
    assertKey(key);
    const full = path.resolve(this.root, key);
    if (!full.startsWith(path.resolve(this.root) + path.sep)) throw new Error('Invalid storage key.');
    return full;
  }

  async put(key: string, bytes: Buffer) {
    const full = this.pathFor(key);
    await mkdir(path.dirname(full), { recursive: true });
    // Write to a temporary name first so a half-written file is never served.
    const temporary = `${full}.${randomBytes(6).toString('hex')}.tmp`;
    await writeFile(temporary, bytes);
    await rename(temporary, full);
  }

  async get(key: string) {
    try {
      return await readFile(this.pathFor(key));
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }
}

/**
 * Production storage: Cloudinary, through its signed REST API. Files are
 * uploaded as `authenticated` assets, so no public URL can open them; the
 * app reads them back with a signed download request and serves them
 * through its own permission-checked routes, exactly as with local disk.
 */
class CloudinaryStorage implements FileStorage {
  constructor(
    private readonly cloudName: string,
    private readonly apiKey: string,
    private readonly apiSecret: string,
  ) {}

  /** Cloudinary's request signature: sorted `key=value` pairs joined by `&`, then the secret, SHA-1. */
  private sign(params: Record<string, string>) {
    const payload = Object.keys(params)
      .sort()
      .map((name) => `${name}=${params[name]}`)
      .join('&');
    return createHash('sha1').update(payload + this.apiSecret).digest('hex');
  }

  /** An image's public id carries no extension; Cloudinary keeps the format separately. */
  private split(key: string) {
    assertKey(key);
    const dot = key.lastIndexOf('.');
    return dot > key.lastIndexOf('/') ? { publicId: key.slice(0, dot), format: key.slice(dot + 1) } : { publicId: key, format: '' };
  }

  async put(key: string, bytes: Buffer, contentType: string) {
    const { publicId } = this.split(key);
    const params = { public_id: publicId, timestamp: String(Math.floor(Date.now() / 1000)), type: 'authenticated' };
    const form = new FormData();
    for (const [name, value] of Object.entries(params)) form.set(name, value);
    form.set('api_key', this.apiKey);
    form.set('signature', this.sign(params));
    form.set('file', new Blob([new Uint8Array(bytes)], { type: contentType }), 'upload');

    const response = await fetch(`https://api.cloudinary.com/v1_1/${this.cloudName}/image/upload`, { method: 'POST', body: form });
    if (!response.ok) {
      const body = (await response.json().catch(() => null)) as { error?: { message?: string } } | null;
      throw new Error(`Cloudinary upload failed (${response.status}): ${body?.error?.message ?? response.statusText}`);
    }
  }

  async get(key: string) {
    const { publicId, format } = this.split(key);
    const params: Record<string, string> = { public_id: publicId, timestamp: String(Math.floor(Date.now() / 1000)), type: 'authenticated' };
    if (format) params.format = format;
    const query = new URLSearchParams({ ...params, api_key: this.apiKey, signature: this.sign(params) });

    const response = await fetch(`https://api.cloudinary.com/v1_1/${this.cloudName}/image/download?${query}`, { cache: 'no-store' });
    if (response.status === 404) return null;
    if (!response.ok) throw new Error(`Cloudinary download failed (${response.status}).`);
    return Buffer.from(await response.arrayBuffer());
  }
}

let storage: FileStorage | null = null;

/**
 * The driver comes from STORAGE_DRIVER ("local" or "cloudinary"). When it
 * isn't set, Cloudinary is used as soon as its credentials are present —
 * a hosted server has no lasting disk to write to.
 */
export function getStorage(): FileStorage {
  if (storage) return storage;
  const { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;
  const driver = process.env.STORAGE_DRIVER ?? (CLOUDINARY_CLOUD_NAME ? 'cloudinary' : 'local');
  if (driver === 'cloudinary') {
    if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_API_SECRET) {
      throw new Error('Cloudinary storage needs CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET.');
    }
    storage = new CloudinaryStorage(CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET);
    return storage;
  }
  if (driver !== 'local') {
    throw new Error(`Storage driver "${driver}" is not available. Use STORAGE_DRIVER=local or cloudinary.`);
  }
  storage = new LocalDiskStorage(process.env.LOCAL_STORAGE_DIR ?? path.join(process.cwd(), '.local-storage'));
  return storage;
}

export type ImageType = { mimeType: 'image/jpeg' | 'image/png' | 'image/webp'; extension: 'jpg' | 'png' | 'webp' };

/** The image type from the file's actual bytes (magic numbers) — never from its name or declared type. */
export function sniffImage(bytes: Buffer): ImageType | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return { mimeType: 'image/jpeg', extension: 'jpg' };
  if (bytes.length >= 8 && bytes.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return { mimeType: 'image/png', extension: 'png' };
  }
  if (bytes.length >= 12 && bytes.subarray(0, 4).toString('latin1') === 'RIFF' && bytes.subarray(8, 12).toString('latin1') === 'WEBP') {
    return { mimeType: 'image/webp', extension: 'webp' };
  }
  return null;
}
